### ISSUE TITLE
Missing Requirements

### ISSUE THREAD

**Issue by curiousmuch** [strictdoc-project/strictdoc#1060]
Installation w/ pipx or pip will not run due to missing requirement bs4. 
```
curiousmuch@ThinkPadT490:~$ pipx install strictdoc
⚠️  Note: strictdoc was already on your PATH at
    /home/curiousmuch/.asdf/shims/strictdoc
  installed package strictdoc 0.0.34, installed using Python 3.10.7
  These apps are now globally available
    - strictdoc
done! ✨ 🌟 ✨
curiousmuch@ThinkPadT490:~$ strictdoc
Traceback (most recent call last):
  File "/home/curiousmuch/.local/bin/strictdoc", line 5, in <module>
    from strictdoc.cli.main import main
  File "/home/curiousmuch/.local/pipx/venvs/strictdoc/lib/python3.10/site-packages/strictdoc/cli/main.py", line 30, in <module>
    from strictdoc.core.actions.export_action import ExportAction
  File "/home/curiousmuch/.local/pipx/venvs/strictdoc/lib/python3.10/site-packages/strictdoc/core/actions/export_action.py", line 13, in <module>
    from strictdoc.export.html.html_generator import HTMLGenerator
  File "/home/curiousmuch/.local/pipx/venvs/strictdoc/lib/python3.10/site-packages/strictdoc/export/html/html_generator.py", line 35, in <module>
    from strictdoc.export.html.tools.html_embedded import HTMLEmbedder
  File "/home/curiousmuch/.local/pipx/venvs/strictdoc/lib/python3.10/site-packages/strictdoc/export/html/tools/html_embedded.py", line 3, in <module>
    import bs4
ModuleNotFoundError: No module named 'bs4'
curiousmuch@ThinkPadT490:~$ pipx inject strictdoc bs4
  injected package bs4 into venv strictdoc
done! ✨ 🌟 ✨
curiousmuch@ThinkPadT490:~$ strictdoc about
=============
= StrictDoc =
=============
Purpose: Software for writing technical requirements specifications.
Version: 0.0.34
Docs:    https://strictdoc.readthedocs.io/en/stable/
Github:  https://github.com/strictdoc-project/strictdoc
License: Apache 2



```

**Comment by stanislaw** [comment]
Could you try the new Pip and let me know if everything works: https://pypi.org/project/strictdoc/? I will close this issue, but feel free to reopen, if any further issues.

**Comment by curiousmuch** [comment]
Fixed! Thank you! Definitely chill out and take a break man. You're responding way too fast :D
