### ISSUE TITLE
strictdoc server temp file permission denied on Windows 10

### ISSUE THREAD

**Issue by richardbarlow** [strictdoc-project/strictdoc#1061]
When running `strictdoc server .` on Windows 10 the following error occurs:

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\a\AppData\Local\pypoetry\Cache\virtualenvs\gp-tooling-z3bRsNaW-py3.11\Scripts\strictdoc.exe\__main__.py", line 7, in <module>
  File "C:\Users\a\AppData\Local\pypoetry\Cache\virtualenvs\gp-tooling-z3bRsNaW-py3.11\Lib\site-packages\strictdoc\cli\main.py", line 142, in main
    raise exc
  File "C:\Users\a\AppData\Local\pypoetry\Cache\virtualenvs\gp-tooling-z3bRsNaW-py3.11\Lib\site-packages\strictdoc\cli\main.py", line 140, in main
    _main(parallelizer)
  File "C:\Users\a\AppData\Local\pypoetry\Cache\virtualenvs\gp-tooling-z3bRsNaW-py3.11\Lib\site-packages\strictdoc\cli\main.py", line 91, in _main
    run_strictdoc_server(
  File "C:\Users\a\AppData\Local\pypoetry\Cache\virtualenvs\gp-tooling-z3bRsNaW-py3.11\Lib\site-packages\strictdoc\server\server.py", line 44, in run_strictdoc_server
    with open(tmp_config_file.name, "wb") as tmp_config_file_:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\A\\AppData\\Local\\Temp\\tmptkm9ci_q'
```

This is due to the fact that the name of a NamedTemporaryFile cannot be used to open the file for writing a second time: https://stackoverflow.com/questions/23212435/permission-denied-to-write-to-my-temporary-file

**Comment by richardbarlow** [comment]
I believe that the re-opening of the file in `server.py` is unnecessary. The `tmp_config_file` object is a file-like object that can be used to write to the temporary file already:
https://github.com/strictdoc-project/strictdoc/blob/ac8455fe7cfa308ea85428988627c6c124fa261f/strictdoc/server/server.py#L41-L46

It's also unclear to me why contact managers are not being used for the optional TemporaryDirectory and this NamedTemporaryFile. If there is an exception raised before the end of the `run_strictdoc_server` function then these temporary directory/files will not be removed.

**Comment by stanislaw** [comment]
Thanks a lot for reporting this! I am not a Windows user, and the Windows support may be weaker in general. This is why I am happy to see Windows-specific feedback 👍 

Now, give me some time to understand your change. The high-level description makes complete sense.

I have also opened a ticket to create a job for running the end-to-end tests on Windows CI: https://github.com/strictdoc-project/strictdoc/issues/1065.

**Comment by stanislaw** [comment]
Thanks for sharing! I was actually going to ask if you hit any other issues, and I am glad to hear that everything works.

I will release your fix ASAP when it is merged.

**Comment by richardbarlow** [comment]
> There is a workaround for this: https://stackoverflow.com/a/15235559. I will try implementing it in the PR and see if it works.

The workaround works! We've now got `strictdoc server` running successfully on Windows 10 :grin:

**Comment by stanislaw** [comment]
Could you try the new Pip and let me know if everything works: https://pypi.org/project/strictdoc/?

**Comment by curiousmuch** [comment]
I can confirm this is fixed on Windows.

**Comment by curiousmuch** [comment]
![image](https://user-images.githubusercontent.com/7798665/227272555-2f0c66c6-a393-451a-9775-c27ae6e90f99.png)
