### ISSUE TITLE
UI section move internal error

### ISSUE THREAD

**Issue by elfman2** [strictdoc-project/strictdoc#1185]
version 0.0.42a6

INFO:     ::1:33206 - "POST /actions/document/move_node HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.9/dist-packages/strictdoc/server/routers/main_router.py", line 1513, in move_node
    output = template.render(
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.9/dist-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/usr/local/lib/python3.9/dist-packages/strictdoc/export/html/templates/actions/document/move_node/stream_update_document_content.jinja", line 3, in top-level template code
    {% include "screens/document/document/frame_document_content.jinja.html" %}
  File "/usr/local/lib/python3.9/dist-packages/strictdoc/export/html/templates/screens/document/document/frame_document_content.jinja.html", line 3, in top-level template code
    {% include "screens/document/document/frame_document_config.jinja.html" %}
  File "/usr/local/lib/python3.9/dist-packages/strictdoc/export/html/templates/screens/document/document/frame_document_config.jinja.html", line 2, in top-level template code
    {%- set sdoc_entity = document -%}
  File "/usr/local/lib/python3.9/dist-packages/strictdoc/export/html/templates/components/node/root.jinja", line 26, in top-level template code
    {%- if config.is_running_on_server and not standalone -%}
jinja2.exceptions.UndefinedError: 'standalone' is undefined

**Comment by stanislaw** [comment]
We are still missing the UI test doing the moves, and this feature escaped my attention during the massive internal refactoring for the Auto-UID feature. But we will find a way to put it under the UI testing.

Thanks for catching this very early!

**Comment by elfman2** [comment]
Checked OK,
Thks
