### ISSUE TITLE
source coverage exception when source file last line is not empty

### ISSUE THREAD

**Issue by elfman2** [strictdoc-project/strictdoc#1307]
INFO:     ::1:50370 - "GET /source_coverage.html HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/applications.py", line 271, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/applications.py", line 118, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/usr/local/lib/python3.9/dist-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/dist-packages/fastapi/routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/usr/local/lib/python3.9/dist-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/usr/local/lib/python3.9/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.9/dist-packages/strictdoc/server/routers/main_router.py", line 2312, in get_incoming_request
    return get_document(request, full_path)
  File "/usr/local/lib/python3.9/dist-packages/strictdoc/server/routers/main_router.py", line 2378, in get_document
    html_generator.export_source_coverage_screen(
  File "/usr/local/lib/python3.9/dist-packages/strictdoc/export/html/html_generator.py", line 400, in export_source_coverage_screen
    document_content = SourceFileViewHTMLGenerator.export(
  File "/usr/local/lib/python3.9/dist-packages/strictdoc/export/html/generators/source_file_view_generator.py", line 55, in export
    ) = SourceFileViewHTMLGenerator.get_pygmented_source_lines(
  File "/usr/local/lib/python3.9/dist-packages/strictdoc/export/html/generators/source_file_view_generator.py", line 157, in get_pygmented_source_lines
    assert len(pygmented_source_file_lines) == len(source_file_lines), (
AssertionError: Something went wrong when running Pygments against the source file: 260 == 261

**Comment by stanislaw** [comment]
This case has been fixed and is available in the alpha version `--pre`. I am taking a note on writing more unit tests against the Pygments generator to finally cover all these cases once and for all.

**Comment by stanislaw** [comment]
As always, thanks for reporting this!
