### ISSUE TITLE
UI: handle server errors 404 and 500

### ISSUE THREAD

**Issue by mettta** [strictdoc-project/strictdoc#1539]

**Comment by aa956** [comment]
Yes, would be useful to quickly catch simple errors like RST markup syntax failures.

Example error (missing space between link label and URL):

```rst
See standard in PDF format `here<https://example.com/>`_
```

`strictdoc export` and `strictdoc server` Web UI editor error handling looks good - single error message in a log and/or in the Web UI.

But starting strictdoc server after error is already in the sdoc and trying to open the affected document throws very long uvicorn log (280+ lines), so actual error (that is logged on top) is almost certainly not visible anymore even on a full screen terminal.

```console
$ strictdoc server .
...
PERF:     GET /assets/favicon.ico 0.001s
INFO:     connection closed
error: problems when converting RST to HTML:
RST markup syntax error on line 1: Unknown target name: "here<https://example.com/>".
RST fragment: >>>
See standard in PDF format `here<https://example.com/>`_

<<<
ERROR:    Exception in ASGI application
  + Exception Group Traceback (most recent call last):
  |   File "/home/user/strictdoc-examples/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi

*** CUT ****

    | anyio.EndOfStream
    | 
    | During handling of the above exception, another exception occurred:
    | 

*** CUT ****

200+ lines

*** CUT ****

  File "/usr/lib/python3.11/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError

```

**Comment by mettta** [comment]
@aa956 Thanks for the detailed report!
The UI side of this is now covered in #2833 - when an RST error causes a server exception, the browser will show a styled 500 error page instead of a raw crash response.

The terminal logging issue (280+ lines of uvicorn traceback burying the actual error) is a separate concern.
@stanislaw , could you take a look and decide if this warrants a new issue?
