### ISSUE TITLE
BUG: UID: loss of graph integrity during Req editing

### ISSUE THREAD

**Issue by mettta** [strictdoc-project/strictdoc#1587]
**How to reproduce:**
1. Open "Add new Requirement" Form,
2. and fill _statement_ as a required field with something.
3. **Change the UID** (set it **to the wrong one**, e.g. equal to the past one, or something like that)
4. Submit the Form (and get an expected error!)
5. **Amend the UID to the correct one**, at which no error should be expected 
6. Submit the Form

**Expectations**: saving without error

**You'll get:**

```

INFO:     127.0.0.1:51383 - "POST /actions/document/create_requirement HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/anyio/streams/memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    self.scope, self.receive, self.send
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "./strictdoc/server/app.py", line 33, in add_process_time_header
    response = await call_next(request)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/fastapi/routing.py", line 274, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "./strictdoc/server/routers/main_router.py", line 873, in create_requirement
    transform.perform()
  File "./strictdoc/core/transforms/create_requirement.py", line 120, in perform
    rhs_node=requirement,
  File "./strictdoc/core/graph_database.py", line 64, in create_link
    lhs_node=lhs_node, rhs_node=rhs_node
  File "./strictdoc/core/graph/one_to_one_dictionary.py", line 30, in create_link
    assert lhs_node not in self._dict
AssertionError

```

**Comment by mettta** [comment]
I also got something that's supposed to be impossible to get.?

![image](https://github.com/strictdoc-project/strictdoc/assets/490084/adfd1748-d554-4047-bc8c-76b87838a20d)

**Comment by mettta** [comment]
After restarting the server I get the error as expected:

```
Step 'Find and read SDoc files' took: 1.16 sec.
Step 'Build traceability graph' start.
error: DocumentIndex: two nodes with the same UID exist in the same document: LOSS-17 in "Losses".
```

However, in the last step, I was able to get **2 nodes with the same UIDs in the SDOC file using the web interface**.

**Comment by mettta** [comment]
in the main branch:
 
 I created a requirement, then edited it and deleted its UID. 
After that, no new requirements are created:

```
assert lhs_node not in self._dict
AssertionError
```
