### ISSUE TITLE
HTML2PDF: UnicodeEncodeError: 'charmap' codec can't encode character '\u02fd' in position 62111: character maps to <undefined>

### ISSUE THREAD

**Issue by npalluat** [strictdoc-project/strictdoc#1773]
Hello,

Following my report in Discord (as Briceus) and your message informing a solution, I tried the version 0.0.54a1 to check your fix, but it crashs when starting the server with the following message:

`
AssertionError: SDocSection(mid = "d71239afbc2742239b47662aecd7ce66", uid = NoneType(...), custom_level = NoneType(...), title = "Main Functionalities", requirement_prefix = NoneType(...), free_texts = [1 elements], section_contents = [2 elements], _tx_position = 4057, _tx_position_end = 4392, parent = SDocDocument(...), reserved_uid = NoneType(...), reserved_title = "Main Functionalities", ng_resolved_custom_level = NoneType(...), ng_level = 1, ng_has_requirements = False, ng_document_reference = DocumentReference(...), ng_including_document_reference = DocumentReference(...), context = SectionContext(...), reserved_mid = "d71239afbc2742239b47662aecd7ce66", mid_permanent = True, ng_whitelisted = True, root_section = False)
` 

I keep the original message for the issue if you want me to do another test.

Regards,
Nicolas

**Comment by stanislaw** [comment]
Thanks for reporting this. Please provide a stack trace if possible.

**Comment by npalluat** [comment]
Yes, here the trace since the command line, I replaced some personal data to other names or windows environment variable names:

```
(%userprofile%\Dev\TOOL\.conda-envs\env-dev) PS %userprofile%\Dev\TOOL> strictdoc server .

******************************************
*               WARNING                  *
*                                        *
* The StrictDoc Web-based user interface *
* is a highly experimental feature.      *
* Things may go wrong, so get ready      *
* to report bugs.                        *
******************************************

WARNING:  Current configuration will not reload as not all conditions are met, please refer to documentation.
Step 'Parse SDoc project tree' start.
Step 'Find and read SDoc files' start.
Reading SDOC: scrs.sdoc ..................................... 0.09s
Reading SDOC: swrs.sdoc ..................................... 0.08s
Reading SDOC: syrs.sdoc ..................................... 0.09s
Reading SDOC: trace.sdoc .................................... 0.08s
Reading SDOC: titleblock.sdoc ............................... 0.14s
Reading SDOC: watt.sdoc ..................................... 0.11s
Step 'Find and read SDoc files' took: 0.85 sec.
Step 'Build traceability graph' start.
Traceback (most recent call last):
  File "%localappdata%\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "%localappdata%\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "%localappdata%\Programs\Python\Python38\Scripts\strictdoc.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "%localappdata%\Programs\Python\Python38\lib\site-packages\strictdoc\cli\main.py", line 195, in main
    raise exc
  File "%localappdata%\Programs\Python\Python38\lib\site-packages\strictdoc\cli\main.py", line 190, in main
    _main(parallelizer)
  File "%localappdata%\Programs\Python\Python38\lib\site-packages\strictdoc\cli\main.py", line 107, in _main
    run_strictdoc_server(
  File "%localappdata%\Programs\Python\Python38\lib\site-packages\strictdoc\server\server.py", line 47, in run_strictdoc_server
    uvicorn.run(
  File "%localappdata%\Programs\Python\Python38\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "%localappdata%\Programs\Python\Python38\lib\site-packages\uvicorn\server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "%localappdata%\Programs\Python\Python38\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "%localappdata%\Programs\Python\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "%localappdata%\Programs\Python\Python38\lib\site-packages\uvicorn\server.py", line 69, in serve
    config.load()
  File "%localappdata%\Programs\Python\Python38\lib\site-packages\uvicorn\config.py", line 439, in load
    self.loaded_app = self.loaded_app()
  File "%localappdata%\Programs\Python\Python38\lib\site-packages\strictdoc\server\app.py", line 88, in strictdoc_production_app
    return create_app(
  File "%localappdata%\Programs\Python\Python38\lib\site-packages\strictdoc\server\app.py", line 55, in create_app        
    create_main_router(
  File "%localappdata%\Programs\Python\Python38\lib\site-packages\strictdoc\server\routers\main_router.py", line 157, in create_main_router
    export_action.build_index()
  File "%localappdata%\Programs\Python\Python38\lib\site-packages\strictdoc\helpers\timing.py", line 14, in wrap
    result = func(*args, **kw)
  File "%localappdata%\Programs\Python\Python38\lib\site-packages\strictdoc\core\actions\export_action.py", line 37, in build_index
    TraceabilityIndexBuilder.create(
  File "%localappdata%\Programs\Python\Python38\lib\site-packages\strictdoc\core\traceability_index_builder.py", line 104, in create
    TraceabilityIndexBuilder.create_from_document_tree(document_tree)
  File "%localappdata%\Programs\Python\Python38\lib\site-packages\strictdoc\helpers\timing.py", line 14, in wrap
    result = func(*args, **kw)
  File "%localappdata%\Programs\Python\Python38\lib\site-packages\strictdoc\core\traceability_index_builder.py", line 683, in create_from_document_tree
    document_from_file_.configure_with_resolved_document(
  File "%localappdata%\Programs\Python\Python38\lib\site-packages\strictdoc\backend\sdoc\models\document_from_file.py", line 54, in configure_with_resolved_document
    assert (
AssertionError: SDocSection(mid = "d71239afbc2742239b47662aecd7ce66", uid = NoneType(...), custom_level = NoneType(...), title = "Main Functionalities", requirement_prefix = NoneType(...), free_texts = [1 elements], section_contents = [2 elements], _tx_position = 4057, _tx_position_end = 4392, parent = SDocDocument(...), reserved_uid = NoneType(...), reserved_title = "Main Functionalities", ng_resolved_custom_level = NoneType(...), ng_level = 1, ng_has_requirements = False, ng_document_reference = DocumentReference(...), ng_including_document_reference = DocumentReference(...), context = SectionContext(...), reserved_mid = "d71239afbc2742239b47662aecd7ce66", mid_permanent = True, ng_whitelisted = True, root_section = False)
(%userprofile%\Dev\TOOL\.conda-envs\env-dev) PS %userprofile%\Dev\TOOL> 
```

**Comment by stanislaw** [comment]
This should be fixed in the just-released 0.0.54a2. Please try with `pip install strictdoc --pre`.

https://github.com/strictdoc-project/strictdoc/pull/1775

**Comment by stanislaw** [comment]
By the way, the composable documents were only implemented recently, and this is why they didn't receive enough testing.

Thanks for testing this, and I also see that you are including fragments inside sections which suggests that the structure of your document is at least non-trivial.

**Comment by npalluat** [comment]
Thanks the 0.0.54a2 solves this issue. I have another one with png images in _assets folder that are not included in the pdf, but I will look first if the answer is not in the documentation.

For the structure, yes, I decided to use strictdoc when you changed the solution from fragment to composable documents as it fits better my needs. The idea is to split the writing of sections of the documents per team/people and the solution of composable documents is perfect as each section has its own file which solves issues in conflict management. It is also an independent document easier to write, manage, review, .... I have also part of the document that will be common with other teams and be able to separate it in another document is perfect, thanks for that. I am only struggling with images since my "section" documents are in subfolders... (yeah I know... not trivial). Maybe we can continue this topic in another discussion topic.

**Comment by stanislaw** [comment]
Thanks for sharing the note about your activity. If you get to using StrictDoc for anything more serious than a simple demo, let us know, @mettta and I are also happy to know that the tool is being used.

Regarding the images, a.k.a assets, you may have noticed the Composable Documents epic: https://github.com/strictdoc-project/strictdoc/issues/1698, and an action point `Check the behavior of Assets.` which is exactly the issue you are referring to.

I will open a separate ticket where I will document the challenge of resolving relative paths when a document can be viewed as both a standalone document and an included document.

Closing this issue, and I will release the new 0.0.54 today.
