### ISSUE TITLE
AssertionError when updating the relation for a requirement

### ISSUE THREAD

**Issue by mettta** [strictdoc-project/strictdoc#1856]
0. Adding a relation to the requirement. Saving. Edit the requirement, ...

```
PERF:     GET /actions/document/edit_requirement?node_id=294a220377c44b0c8b3a28d701e83509&context_document_mid=e6937884e2e84bbf83749446b9fe1c01 0.006s
INFO:     127.0.0.1:59505 - "GET /actions/document/edit_requirement?node_id=294a220377c44b0c8b3a28d701e83509&context_document_mid=e6937884e2e84bbf83749446b9fe1c01 HTTP/1.1" 200 OK
```

1. change the relationship UID, try to save.
2. get an **error** 
- the error is visible in the console, see the code below; 
- nothing happens in the UI at this time,
- **relation is actually updated** (if you close the form at this step, you can see it). 
It's just that the UI doesn't close the form, and there are errors in the console.

```
INFO:     127.0.0.1:59513 - "POST /actions/document/update_requirement HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/anyio/streams/memory.py", line 98, in receive
    return self.receive_nowait()
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/anyio/streams/memory.py", line 93, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/base.py", line 78, in call_next
    message = await recv_stream.receive()
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/anyio/streams/memory.py", line 118, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 436, in run_asgi
    self.scope, self.receive, self.send
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
  File "./strictdoc/server/app.py", line 34, in add_process_time_header
    response = await call_next(request)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/base.py", line 84, in call_next
    raise app_exc
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/fastapi/routing.py", line 274, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/Users/mettta/Projects/dev/strictdoc-project/strictdoc/build/tox/py37-development/lib/python3.7/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "./strictdoc/server/routers/main_router.py", line 1154, in document__update_requirement
    update_command.perform()
  File "./strictdoc/core/transforms/update_requirement.py", line 177, in perform
    role=reference_id_to_remove_role,
  File "./strictdoc/core/traceability_index.py", line 844, in remove_requirement_parent_uid
    document, parent_requirement_document
  File "./strictdoc/core/traceability_index.py", line 736, in update_disconnect_two_documents_if_no_links_left
    assert requirement_node.reserved_uid is not None
AssertionError
```

4. Clicking the “save” button again successfully saves the requirement with the updated relationship.

```
Published: My try ........................................... 0.06s
PERF:     POST /actions/document/update_requirement 0.073s
INFO:     127.0.0.1:59537 - "POST /actions/document/update_requirement HTTP/1.1" 200 OK
```

**Comment by mettta** [comment]
The described error appears only if the document has a TEXT node without a UID.

**Comment by stanislaw** [comment]
Fixed along with all other changes in https://github.com/strictdoc-project/strictdoc/pull/1862.
