### ISSUE TITLE
Enable testing on older Linux distributions

### ISSUE THREAD

**Issue by stanislaw** [strictdoc-project/strictdoc#325]
One user has reported problems on Ubuntu 16, at least two issues:

1) Having troubles when installing Poetry.
2) Problem installing `xlsxwriter`.

**Comment by RobertoBagnara** [comment]
I have tried installing strictdoc on Ubuntu 16.04 following both routes described in https://strictdoc.readthedocs.io/en/latest/StrictDoc.html#installing-strictdoc-as-a-pip-package .  Here are a few more details.

1. With Poetry

I have first installed Poetry with the command given in https://python-poetry.org/docs/ .
Then I obtained an error as follows:

roberto@zoltan:/usr/local/distrib/strictdoc(master)$ poetry install
Creating virtualenv strictdoc-VOB_9fkv-py3.6 in /home/roberto/.cache/pypoetry/virtualenvs

  ModuleNotFoundError

  No module named 'virtualenv.seed.via_app_data'

  at <frozen importlib._bootstrap>:953 in _find_and_load_unlocked

2. Without Poetry

I did "sudo -H pip install invoke pytest pytidylib html5lib", and then I obtained an error as follows:

roberto@zoltan:/usr/local/distrib/strictdoc(master)$ python3 strictdoc/cli/main.py
Traceback (most recent call last):
  File "strictdoc/cli/main.py", line 10, in <module>
    from strictdoc.core.actions.export_action import ExportAction
  File "strictdoc/cli/../../strictdoc/core/actions/export_action.py", line 7, in <module>
    from strictdoc.export.excel.excel_generator import ExcelGenerator
  File "strictdoc/cli/../../strictdoc/export/excel/excel_generator.py", line 5, in <module>
    import xlsxwriter
ModuleNotFoundError: No module named 'xlsxwriter'

I have then tried to install the missing module as follows:

roberto@zoltan:/usr/local/distrib/strictdoc(master)$ sudo -H pip install xslxwriter
Collecting xslxwriter
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 353, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python3/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python3/dist-packages/pip/index.py", line 795, in get_page
    resp.raise_for_status()
  File "/usr/share/python-wheels/requests-2.18.4-py2.py3-none-any.whl/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://pypi.org/simple/xslxwriter/
