### ISSUE TITLE
SDoc to Reqif conversion for sandbox sdoc file fails

### ISSUE THREAD

**Issue by fkromer** [strictdoc-project/strictdoc#582]
When I execute `strictdoc export --formats=reqif-sdoc ./developer/sandbox/sandbox.sdoc` in the project root dir on Linux to convert the sandbox sdoc file into reqif format I get:

```
Parallelization: Enabled
Step 'Export' start
Step 'Find and read SDoc files' start
Reading SDOC: sandbox.sdoc .................................. 0.07s
Step 'Find and read SDoc files' took: 0.07 sec
Step 'Collect traceability information' start
Step 'Collect traceability information' took: 0.01 sec
Traceback (most recent call last):
  File "/home/florian/.cache/pypoetry/virtualenvs/strictdoc-tbPpW_VZ-py3.9/bin/strictdoc", line 33, in <module>
    sys.exit(load_entry_point('strictdoc', 'console_scripts', 'strictdoc')())
  File "/home/florian/Documents/github/strictdoc/strictdoc/cli/main.py", line 86, in main
    raise exc
  File "/home/florian/Documents/github/strictdoc/strictdoc/cli/main.py", line 84, in main
    _main(parallelizer)
  File "/home/florian/Documents/github/strictdoc/strictdoc/cli/main.py", line 54, in _main
    export_action.export(config, parallelizer)
  File "/home/florian/Documents/github/strictdoc/strictdoc/helpers/timing.py", line 14, in wrap
    result = func(*args, **kw)
  File "/home/florian/Documents/github/strictdoc/strictdoc/core/actions/export_action.py", line 128, in export
    ReqIFExport.export(
  File "/home/florian/Documents/github/strictdoc/strictdoc/backend/reqif/reqif_export.py", line 19, in export
    reqif_bundle = SDocToReqIFObjectConverter.convert_document_tree(
  File "/home/florian/Documents/github/strictdoc/strictdoc/backend/reqif/export/converter.py", line 245, in convert_document_tree
    spec_object = cls._convert_requirement_to_spec_object(
  File "/home/florian/Documents/github/strictdoc/strictdoc/backend/reqif/export/converter.py", line 341, in _convert_requirement_to_spec_object
    field_value = escape(
  File "/home/florian/Documents/github/strictdoc/strictdoc/helpers/string.py", line 27, in escape
    return string.encode("unicode_escape").decode("utf-8")
AttributeError: 'NoneType' object has no attribute 'encode'
```

**Comment by stanislaw** [comment]
This is expected because the implemented set of features is only within what has been tested here so far: https://github.com/strictdoc-project/strictdoc/tree/main/tests/integration/reqif/native/end_to_end. There is a support for more basic documents but not tested yet again larger docs like these that you have tried.

Your report is a good reminder about the next steps 👍
